[package]
name = "jittr"
version = "0.1.0"
edition = "2021"
authors = ["Mara Schulke mara.schulke@hum-systems.com"]

[dependencies]
futures = "0.3"
rtp = { version = "0.6", optional = true }

[features]
default = ["rtp"]
